url: "https://sotaro.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "sotaro.io" # the name of your site, e.g. ACME Corp.

collections:
  posts:
    output: true
    permalink: /posts/:title
  ja:
    output: true
    permalink: /ja/:title
  journals:
    output: true
    permalink: /daily/:title
  photos:
    output: true
    permalink: /photos/:title

defaults:
    - scope:
        type: "posts"
      values:
          layout: "post"
    - scope:
        type: "ja"
      values:
          layout: "post"
    - scope:
        type: "posts"
      values:
          layout: "post"
    - scope:
        type: "journals"
      values:
          layout: "post"
    - scope:
        type: "photos"
      values:
          layout: "photo"
