url: "https://sotaro.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "sotaro.io" # the name of your site, e.g. ACME Corp.
name: sotaro.io (ja)
description: Random notes about random things
url: https://sotaro.io

collections:
  posts:
    output: true
    permalink: /posts/:title
  ja:
    output: true
    permalink: /ja/:title
  journals:
    output: true
    permalink: /daily/:year-:month-:day
  photos:
    output: true
    permalink: /photos/:title
  reading:
    output: true
    permalink: /reading/:title
  travel:
    output: true
    permalink: /travel/:year-:month-:day-:title
  coffee:
    output: true
    permalink: /coffee/:title
  tldrs:
    output: true
    permalink: /tldrs/:title

defaults:
    - scope:
        type: "posts"
      values:
          layout: "post"
    - scope:
        type: "ja"
      values:
          layout: "post"
    - scope:
        type: "posts"
      values:
          layout: "post"
    - scope:
        type: "journals"
      values:
          layout: "journal"
    - scope:
        type: "travel"
      values:
          layout: "post"
    - scope:
        type: "coffee"
      values:
          layout: "post"
    - scope:
        type: "reading"
      values:
          layout: "book"
    - scope:
        type: "photos"
      values:
          layout: "photo"
    - scope:
        type: "tldrs"
      values:
          layout: "tldr"
